### ISSUE TITLE
Cluster init failure is marked as a Warning

### ISSUE THREAD

**Issue by dastergon** [openshift/rosa#332]
Due to a personal misconfiguration `rosa init` failed to init a cluster.  However, the failure was reported as a `W:` (warning).  I am using rosa v1.0.5.

```
❯ rosa init
I: Logged in as 'pratis.openshift' on 'https://api.openshift.com'
I: Validating AWS credentials...
I: AWS credentials are valid!
I: Validating SCP policies...
I: AWS SCP policies ok
I: Validating AWS quota...
I: AWS quota ok
I: Ensuring cluster administrator user 'osdCcsAdmin'...
I: Admin user 'osdCcsAdmin' created successfully!
I: Validating SCP policies for 'osdCcsAdmin'...
I: AWS SCP policies ok
I: Validating cluster creation...
W: Cluster creation failed. If you create a cluster, it should fail with the following error:
In order to run Red Hat OpenShift Service on AWS you need to enable the service in the AWS Console. Please visit https://console.aws.amazon.com/rosa/
I: Verifying whether OpenShift command-line tool is available...
W: Current OpenShift Client Version: v4.7.5
W: Your version of the OpenShift command-line tool is not supported.
Run 'rosa download oc' to download the latest version, then add it to your PATH.
```

I would assume an `E:` to be returned once cluster init fails since it is a hard requirement. What do you think?

**Comment by vkareh** [comment]
@dastergon - This doesn't actually create a cluster, it just does a dry-run of cluster creation to see if it would fail or not when actually creating a cluster (through the `rosa create cluster` command). The `rosa init` command just preps the account and checks that everything is in order to create the cluster. In this case, your account is set up with quota and permissions, but still need access to the ROSA product itself.

Regardless, I think you bring up a good point. The account is _not_ actually ready to create a cluster, so maybe this should be an error output, rather than a warning.

**Comment by dastergon** [comment]
Thanks for the quick reply @vkareh. I am aware of the steps, I just thought that showing a warning is a bit misleading. Hope it's an easy fix.
