### ISSUE TITLE
Automatic resource tagging

### ISSUE THREAD

**Issue by teroahonen-vungle** [openshift/rosa#433]
Currently, ROSA doesn't support AWS resource tagging. Are there any plans to include support for tagging? There are two "layers" of tagging needed.

1. Resources created during install, VPC, subnet, *LB, etc.
2. Resources created when using ROSA, EBS, EC2 instances, new LBs.

**Comment by acathrow** [comment]
The ROSA (through the OpenShfift installer) tags the resources it creates with two tags:
key: Name Value: name of cluster
key" kubernetes.io/cluster/{cluster-name} Value =- owned 
These tags apply to EC2 instances, EBS, LBs, etc
If an item is used but not created, eg deploying into an existing VPC then a shared tag is added, then later removed from the VPC.
Resource created later (new machine pools, LBs, etc) all get the same tags.
This all happens automatically.

OpenShift supports allowing passing custom tags to the installer which will add those extra tags to the objects created at install time but does not guarantee that objects created post-installation will be tagged.
Openshift RFE [2012](https://issues.redhat.com/browse/RFE-2012) along with a couple of others referenced in that RFE outline the path to fully support custom tags throughout the cluster's lifecycle.

We realized that this RFE is not on the ROSA RFE github project: https://red.ht/rosa-roadmap so it has been added.

If you have any further questions or clarifications please can you add a comment to the issue here:
https://github.com/openshift-cs/managed-openshift/issues/42
